service: position-sizer-ea-command-center

plugins:
  - serverless-dynamodb-local
  - serverless-offline # needs to be last in the list

provider:
  name: aws
  runtime: nodejs20.x
  stage: production
  region: us-east-1
  logRetentionInDays: 14
  memorySize: 256 # default is 1024 MB
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": ["StatusDynamoDBTable", "Arn" ] }
  environment:
    STATUS_TABLE: ${self:custom.tableName}

custom:
  tableName: 'position-sizer-ea-command-center'
  dynamodb:
    start:
      migrate: true
    stages:
      - production

functions:
  root:
    handler: index.handler
    events:
      - http: GET /
      - http: 'ANY /{proxy+}'
  get:
    handler: index.handler
    events:
      - http: 'GET /get'
  set:
    handler: index.handler
    events:
      - http: 'GET /set/{proxy+}'

resources:
  Resources:
    StatusDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: envName
            AttributeType: S
        KeySchema:
          -
            AttributeName: envName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}